# Autogenerated wrapper script for libsvm_jll for x86_64-w64-mingw32
export libgomp, libsvm, svm_predict, svm_scale, svm_train

JLLWrappers.@generate_wrapper_header("libsvm")
JLLWrappers.@declare_library_product(libgomp, "libgomp-1.dll")
JLLWrappers.@declare_library_product(libsvm, "libsvm.dll")
JLLWrappers.@declare_executable_product(svm_predict)
JLLWrappers.@declare_executable_product(svm_scale)
JLLWrappers.@declare_executable_product(svm_train)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libgomp,
        "bin\\libgomp-1.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libsvm,
        "bin\\libsvm.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        svm_predict,
        "bin\\svm-predict.exe",
    )

    JLLWrappers.@init_executable_product(
        svm_scale,
        "bin\\svm-scale.exe",
    )

    JLLWrappers.@init_executable_product(
        svm_train,
        "bin\\svm-train.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
